### ISSUE TITLE
context.expose is not a function

### ISSUE THREAD

**Issue by mimnot** [logue/vue-codemirror6#15]
Hi,

I'm trying to use vue-codemirror6 with a Vue 2.6.14 project.
Unfortunately, I'm getting the following error

```
TypeError: context.expose is not a function
```

![image](https://user-images.githubusercontent.com/71828281/224362550-410391bf-3a72-408c-9249-a6a06a976e25.png)

Any clue how to resolve this ?

**Comment by logue** [comment]
For projects below 2.7, `@vue/composition-api` is required separately. See the [@vue/composition-api](https://github.com/vuejs/composition-api) site for details.

**Comment by mimnot** [comment]
Sorry, I should have precise that I installed `@vue/composition-api` as recommended.

Anyway, I reset everything and tried one of the example provided in the README file.

```vue
<template>
    <code-mirror v-model="value" />
</template>
<script>
import { ref, defineComponent } from '@vue/composition-api'
import CodeMirror from 'vue-codemirror6'

export default defineComponent({
  components: {
    CodeMirror
  },
  setup () {
    const value = ref('Cozy lummox gives smart squid who asks for job pen.')
    return { value }
  }
})
</script>

```

Yet the same errors occur

```
[Vue warn]: Error in data(): "TypeError: context.expose is not a function"
```
```
TypeError: context.expose is not a function
```

**Comment by logue** [comment]
Vue2 does not support `expose` in the first place, and although it exists as a function in Vue2.7, it seems to behave the same as return of the `setup` function.

I think it will either require vue 2.7 or higher, or it will be an implementation that separates it with an if statement, but considering that [vue 2 will be EOL at the end of this year](https://v2.vuejs.org/lts/), the policy will be the former.

**Comment by mimnot** [comment]
Initially, I wanted to avoid the hassle of migrating, but I think I'll just move to Vue 2.7.

Thanks for your help
