### ISSUE TITLE
CodeMirror plugin crashed: TypeError: config2.needsRefresh is not a function

### ISSUE THREAD

**Issue by Fluttercom** [logue/vue-codemirror6#19]
Getting this exception, while initializing CodeMirror with jsonParseLinter.
`<CodeMirror v-model="f.Content" basic :lang="Lang" :linter="jsonLinter"></CodeMirror>`

```
<script setup lang="ts">
import CodeMirror from "vue-codemirror6"
import { xml } from '@codemirror/lang-xml'
import { json, jsonParseLinter } from '@codemirror/lang-json'

let Lang = json()
const jsonLinter = jsonParseLinter()
```

index.js:1898 CodeMirror plugin crashed: TypeError: config2.needsRefresh is not a function
    at Object.update (index.js:214:43)
    at PluginInstance.update (index.js:1984:32)
    at EditorView.updatePlugins (index.js:6819:29)
    at EditorView.update (index.js:6725:22)
    at EditorView._dispatch (index.js:6583:59)
    at EditorView.dispatch (index.js:6651:14)
    at watch.immediate (index.es.js:372:20)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at job (runtime-core.esm-bundler.js:1756:9)

**Comment by logue** [comment]
try this.

```vue
<script setup lang="ts">
import { ref, type Ref } from 'vue';
import CodeMirror from "vue-codemirror6"
import { json, jsonParseLinter } from '@codemirror/lang-json'

const content: Ref<string> = ref();
</script>
<template>
  <code-mirror v-model="content" basic :lang="json" :linter="jsonParseLinter" />
</template>
```

**Comment by Fluttercom** [comment]
No difference with neither static nor reactive model.

**Comment by logue** [comment]
In that case, hooking to `onMounted` may work.

Below is pseudo code.

```vue
<template>
    <div v-if="ready" style="min-width: 150px; min-height: 150px;">
        <code-mirror v-model="content" basic :lang="json()" :linter="jsonParseLinter()" />
    </div>
</template>

<script setup lang="ts">
import { ref, type Ref } from 'vue';
import CodeMirror from "vue-codemirror6"
import { json, jsonParseLinter } from '@codemirror/lang-json'

const ready: Ref<boolean> = ref(false);
const content: Ref<string> = ref('{ "test": "value" }');

onMounted(()=> {
  ready.value = true;
});
</script>
```

**Comment by Fluttercom** [comment]
Tried above - no luck.

**Comment by tminich** [comment]
The issue is that the default value for `linterConfig` is broken. it sets `needsRefresh` to `true`, but code mirror expects a function (https://codemirror.net/docs/ref/#lint.linter%5Econfig). Workaround is setting `:linter-config="{}"` on the CodeMirror component.

**Comment by Fluttercom** [comment]
Thanks, this resolved the issue.
