### ISSUE TITLE
Possible Regression/Compromise in 1.2.x?

### ISSUE THREAD

**Issue by BusterNeece** [logue/vue-codemirror6#29]
Hello!

I use this library in my web application, which is distributed to users and self-hosted by them.

On a development environment, I've encountered no problems with the library, including with the latest version (1.2.3). In production, however, I am able to reliably reproduce an infinite loop that crashes any browser. We were previously on the last 1.1.x version, so it's possible that this issue was introduced in the 1.2.x version series.

I'm also somewhat concerned that there are no tagged releases here on GitHub for the 1.2.x version series, though there are corresponding commits. I'm also experiencing somewhat of a strange issue on the project's homepage, where every two or three refreshes the entire code section disappears from view. Together, this has me worried that the project has been compromised in some way.

I can try to produce logs, but documenting and logging infinite loop crashes is notoriously hard to do with client-side JavaScript, but I'll do my best. Just wanted to make the maintainers here aware of the issue.

**Comment by logue** [comment]
When I checked, the problem occurred with Vue 3.4 series.

As a temporary workaround, try downgrading Vue to 3.3 or updating vue-codemirror6 to 1.1.x.

**Comment by logue** [comment]
Fixed in current version

**Comment by BusterNeece** [comment]
@logue Thank you! Sorry for the ticket suggesting there may have been a compromise; I saw a release on NPM that I didn't see a corresponding release for here, and the error looked a lot like it was using excessive CPU, which might've been suspicious.
