### ISSUE TITLE
No have `index.d.ts` file in the dist folder at version@latest.

### ISSUE THREAD

**Issue by imguolao** [logue/vue-codemirror6#5]
version: 0.6.2

**Comment by imguolao** [comment]
https://github.com/logue/vue-codemirror6/blob/711a6fbe967c03c6566f583778086c6370af6a8f/package.json#L49

**Comment by logue** [comment]
Fixed in `0.6.3`.
The cause was that the build in analyze mode was published as it was.

**Comment by callym** [comment]
I think this has happened again with `1.1.28`, `1.1.27` seems fine
