### ISSUE TITLE
updating lang prop doesn't update the editor

### ISSUE THREAD

**Issue by Motarack** [logue/vue-codemirror6#6]
Hey, thanks a lot for the package.

I'm still new to vue so I might be missing something, but it seems that updating the lang prop doesn't update the editor, what I'm trying to achieve is to have a drop list next to the editor where you select the language, and the language support of the editor should update based on that(by editor I mean codemirror), currently I'm updating the dark prop when the language changes as a workaround.

Is having the editor not update language support when the lang prop value is updated intended, or am I missing something? I'm using vue 3.

**Comment by logue** [comment]
`0.6.7` has been released. It corresponded by making all the values of props the monitoring target.
